package projecteulerproblem2;

/*Ryan Lubin
 *April 13 2018
 *
 *https://projecteuler.net/problem=2
 *Problem 2
 *Even Fibonacci Numbers
 *
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
 
import java.util.*;

public class ProjectEulerProblem2 {

	public static void main(String[] args) {
		
		//make an array
		//put all the numbers in the array
		//add put the array
		List<Integer> list = new ArrayList<>();
		list.add(1);
		list.add(2);
		int count = 2;
		
		//while the current element does not exceed 4 million
		while(true) {
			int i = list.get(list.size() - 2) + list.get(list.size() - 1);
			if(i % 2 == 0) {
				count += i;
			}
			if(i > 4000000) {
				break;
			}
			list.add(i);
		}
		
		System.out.println(count);
		
	}

}
