package projecteulerproblem12;

/*Ryan Lubim
 *April __ 2018
 *
 *https://projecteuler.net/problem=12
 *Highly Divisble Triangular Number
 *
 *The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *Let us list the factors of the first seven triangle numbers:
 *1: 1
 *3: 1,3
 *6: 1,2,3,6
 *10: 1,2,5,10
 *15: 1,3,5,15
 *21: 1,3,7,21
 *28: 1,2,4,7,14,28
 *We can see that 28 is the first triangle number to have over five divisors.
 *What is the value of the first triangle number to have over five hundred divisors?
 */
 
 public class ProjectEulerProblem12 {
	 
	public static void main(String[] args) {

		long tn = 0;//triangluar number
		long factors = 500;
		
		for(long i = 1; ; ++i) {
			tn += i;
			//System.out.println(tn);
			if(factors(tn) > factors) {
				break;
			}
			//System.out.println();
		}
		
		System.out.println("\nThe first triangular number with more than " + factors + " factors is: " + tn);

	}

	public static long factors(long num) {
		long n = 0;//number of factors
		for(long i = 1; i <= num; ++i) {
			if(num % i == 0) {
				//System.out.println(i);
				++n;
			}
		}
		//System.out.println("n = " + n);
		return n;
	}
	
 }