OPTIONS = ['SPX',
           'VIX',
           'SPY',
           'IWM',
           'QQQ',
           'XLF',
           'SLV',
           'AAPL',
           'TSLA',
           'BAC',
           'AWD',
           'BA',
           'MSFT',
           'WFC',
           'CSCO',
           'AAL',
           'GE',
           ]
